# Generated by Django 4.1.4 on 2023-07-08 07:00

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Annotator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annotatorName",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "annotatorPassword",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "annotatorEmail",
                    models.CharField(blank=True, default="", max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Basemodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelName", models.CharField(blank=True, default="", max_length=100)),
                ("modelType", models.CharField(blank=True, default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datasetName",
                    models.CharField(blank=True, default="", max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fabric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fabricName",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "fabricDescription",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                ("GSM", models.CharField(blank=True, default="", max_length=100)),
                ("color", models.CharField(blank=True, default="", max_length=100)),
                (
                    "fabricType",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("material", models.CharField(blank=True, default="", max_length=100)),
                (
                    "sampleImages",
                    models.ImageField(
                        blank=True, default="", upload_to=api.models.sample_path
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="YoloModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelName", models.CharField(blank=True, default="", max_length=100)),
                ("epochs", models.IntegerField(default=10)),
                ("imgsz", models.IntegerField(default=640)),
                (
                    "baseModel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.basemodel"
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.dataset"
                    ),
                ),
                (
                    "fabric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.fabric"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Imagegallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imageType", models.CharField(blank=True, default="", max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="", upload_to=api.models.image_path
                    ),
                ),
                (
                    "imageLabel",
                    models.FileField(
                        blank=True, default="", upload_to=api.models.label_path
                    ),
                ),
                (
                    "annotator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.annotator"
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.dataset"
                    ),
                ),
                (
                    "fabric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.fabric"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dataset",
            name="fabric",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.fabric"
            ),
        ),
    ]
