# Generated by Django 4.1.4 on 2023-07-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_predictiondata_imageannotated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictiondata",
            name="confidence",
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
