# Generated by Django 4.1.4 on 2023-07-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_dataset_tasks"),
    ]

    operations = [
        migrations.RemoveField(model_name="annotator", name="annotatorPassword",),
        migrations.AddField(
            model_name="annotator",
            name="annotatorId",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
