# Generated by Django 4.1.4 on 2023-07-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_annotator_annotatorpassword_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fabric",
            name="labels",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
